# Generated by Django 4.2.2 on 2023-06-21 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ensamble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procesador', models.CharField(max_length=100)),
                ('memoria_ram', models.CharField(max_length=100)),
                ('disco_duro', models.CharField(max_length=100)),
                ('tarjeta_video', models.CharField(max_length=100)),
                ('fuente_poder', models.CharField(max_length=100)),
            ],
        ),
    ]
